test_run: False
output_dir: "qwen"
trial_rounds: 1
models:
 - "local:Qwen/Qwen2.5-32B-Instruct"
solver:
  #system_prompt: "You are a math expert." 
  parse_feedback: False
  check_feedback: False
  error_string: "The solution parser encountered the following error:\n{error}\nPlease format your reply accurately."
  max_feedback_rounds: 0
  formatting_prefix: "Format your reply as follows:"
inference:
  temperature: 0.7
  top_p: 0.95
  max_tokens: 32768
  concurrent_requests: 20
  timeout: 10000000
problems:
  - ".*"
n_variations: 1
solver_batch_size: 80