test_run: False
output_dir: "mathconstruct_results/no-thinking/variations_1/max_10000_budget_forcing"
trial_rounds: 8
models:
 - "local:deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"
solver:
  #system_prompt: "You are a math expert." 
  parse_feedback: False
  check_feedback: False
  error_string: "The solution parser encountered the following error:\n{error}\nPlease format your reply accurately."
  max_feedback_rounds: 0
  formatting_prefix: "Format your reply as follows:"
  assistant_prefix: "<think>\nOkay I have finished thinking.\n</think>\nLet's solve the problem."
  budget_forcing: "\n\nFinal answer: the final answer is"
inference:
  temperature: 0.6
  top_p: 0.95
  max_tokens: 10000
  concurrent_requests: 20
  timeout: 10000000
problems:
  - ".*"
n_variations: 1
solver_batch_size: 80