test_run: False
output_dir: "r1-qwen/thinking"
trial_rounds: 1
models:
 - "local:deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"
solver:
  #system_prompt: "You are a math expert." 
  parse_feedback: False
  check_feedback: False
  error_string: "The solution parser encountered the following error:\n{error}\nPlease format your reply accurately."
  max_feedback_rounds: 0
  formatting_prefix: "Format your reply as follows:"
  user_template: "{} You should carefully think about the problem and reason step by step."
inference:
  temperature: 0.6
  top_p: 0.95
  max_tokens: 32768
  concurrent_requests: 20
  timeout: 10000000
problems:
  - ".*"
n_variations: 2