test_run: False
output_dir: "thinking/variations_1/max_3000_budget_forcing/pass_at_16"
trial_rounds: 16
models:
 - "local:deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"
solver:
  #system_prompt: "You are a math expert." 
  parse_feedback: False
  check_feedback: False
  error_string: "The solution parser encountered the following error:\n{error}\nPlease format your reply accurately."
  max_feedback_rounds: 0
  formatting_prefix: "Format your reply as follows:"
  user_template: "{} You should carefully think about the problem and reason step by step."
inference:
  temperature: 0.6
  top_p: 0.95
  max_tokens: 3000
  concurrent_requests: 20
  timeout: 10000000
  chat_template: "chat_template.jinja"
  budget_forcing: "\n\nFinal answer: the final answer is"
problems:
  - ".*"
n_variations: 1
solver_batch_size: 150